version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - search

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - search

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - search

  kib01:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - search

  search_api:
    build: .
    container_name: search_api
    ports:
      - 4567:4567
    networks:
      - search
    volumes:
      - .:/app

  metarank:
    image: metarank/metarank:latest
    command: standalone --config /opt/metarank/config.yml --data /opt/metarank/events.jsonl.gz
    ports:
      - 8080:8080
    volumes:
      - ./metarank:/opt/metarank
    networks:
      - search
    environment:
       - "JAVA_OPTS=-Xms5g -Xmx5g"

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

  

networks:
  search:
    driver: bridge